#!/usr/bin/env bash

######################################################################
#
# Intended usage for onboarding developers:
#
# 1. Clone this repository
# 2. Run task/install
# 3. Run task/run
#
# And you should see this project running successfully on your machine.
# (If you do not, please file an issue and let us know.)
#
# The install task:
#
# - Asks to install the elementary OS development libraries
#   if they don’t already exist on your machine.
#
# - Asks to install recommended VSCodium Vala development and debugging
#   extensions (Vala, Meson, CodeLLDB, XML, YAML) if you have VSCodium
#   installed and are missing any of them.
#
# - Installs all required dependencies for the project to compile.
#
# - Configures the Meson build.
#
# - Builds and installs the application using Ninja.
#
# - Updates your system’s icon cache so the application icon displays
#   properly in the Applications Menu and elsewhere.
#
######################################################################

set -eu -o pipefail

# Ask to install the elementary OS development libraries
# if they don’t already exist on your machine.

elementary_sdk_status=$(/usr/bin/dpkg-query --show --showformat='${db:Status-Status}\n' 'elementary-sdk' 2> /dev/null)
if [[ $elementary_sdk_status != 'installed' ]]; then
  install_elementary_sdk_question=$(zenity --question --text='<big>The elementary OS development libraries are not installed.</big>\n\n<b>Install them now?</b>' --title='Watson' --width=250 --icon-name=applications-development)
  install_extensions=$?
  if [[ $install_extensions == 0 ]]; then
    sudo apt install elementary-sdk
  fi
else
  echo '✓ elementary OS development libraries found.'
fi

# Install dependencies.

# If your app has any third-party dependencies that are not included in
# the elementary OS Software Development Kit (SDK) metapackage, add installation
# commands for them here.
#
# For a list of the packages that are included in the elementary OS SDK, see
# https://github.com/elementary/metapackages/blob/master/elementary-sdk-amd64
# https://github.com/elementary/metapackages/blob/master/elementary-sdk-arm64
# https://github.com/elementary/metapackages/blob/master/elementary-sdk-armhf



# Configure build.
meson build --prefix=/usr

# Create translations.

# (This only needs to be done on initial project generation, otherwise it
# results in a dirty git repository due to timestamps if run after a clone.
# The default is not to create/update translations on install.)
if [[ ${1-'do-not-create-translations'} == '--create-translations' ]]; then
  task/update-translations --no-status
  echo '✓ Created translations.'
fi

# Run build and install assets.
pushd build
ninja
ninja install
popd

# Clear icon caches.
sudo update-icon-caches /usr/share/icons/*

echo 'Granite Wallpaper Test App is installed.'
echo ''
echo 'You can run it from the Applications Menu or using the task/run script.'
